name: Mac Build test

on: [push]

jobs:
  test-github-cpuonly:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: SCP test
        uses: appleboy/scp-action@master
        with:
          host: "homes.cels.anl.gov"
          username: "kimk"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: "logins.cels.anl.gov"
          proxy_username: "kimk"
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "ddo/hello.txt"
          target: "hello.txt"
      - name: Check local file
        run: |
          ls -al
          cat hello.txt
