name: Mac Build test

on: [push]

jobs:
  test-github-cpuonly:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        compiler: [gcc, clang] 

    steps:
      - name: Brewing
        run: |
          brew update
          brew install tbb
      - name: Set my secrets
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Checkout DSPThirdPartyLibs
        run: |
          git clone git@xgitlab.cels.anl.gov:kimk/DSPThirdPartyLibs.git
      - name: Test SCIP
        env:
          FC: gfortran-9
        run: |
          cd DSPThirdPartyLibs
          sh SCIPOptSuite-7.0.1-Darwin-no-Ipopt.sh --skip-license
          export DYLD_LIBRARY_PATH=$PWD/lib:$(dirname `$FC --print-file-name libgfortran.dylib`):$DYLD_LIBRARY_PATH
          echo "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
          ls bin
          ls lib
          ./bin/scip -v
      - name: Check SCIP
        run: |
          echo "TEST: ${{ env.DYLD_LIBRARY_PATH }}"
          export DYLD_LIBRARY_PATH=${{ env.DYLD_LIBRARY_PATH }}
          cd DSPThirdPartyLibs
          ls bin
          ls lib
          ./bin/scip -v
