name: Mac Build test

on: [push]

jobs:
  test-github-cpuonly:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04]
        compiler: [gcc, clang] 

    steps:
      - name: Brewing
        run: |
          if [ ${{ matrix.os }} == macos-latest ]
          then
            brew update
            brew install tbb
          fi
      - name: Set my secrets
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Checkout DSPThirdPartyLibs
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan xgitlab.cels.anl.gov >> ~/.ssh/known_hosts
          git clone git@xgitlab.cels.anl.gov:kimk/DSPThirdPartyLibs.git
      - name: Test SCIP
        env:
          FC: gfortran-9
        run: |
          cd DSPThirdPartyLibs
          ./github.sh
          if [ ${{ matrix.os }} == ubuntu-18.04 ]
          then
            export LD_LIBRARY_PATH=$PWD/lib:$(dirname `$FC --print-file-name libgfortran.so`):$LD_LIBRARY_PATH
            echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $GITHUB_ENV
          fi
          if [ ${{ matrix.os }} == macos-latest ]
          then
            export DYLD_LIBRARY_PATH=$PWD/lib:$(dirname `$FC --print-file-name libgfortran.dylib`):$DYLD_LIBRARY_PATH
            echo "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
          fi
      - name: Check SCIP
        run: |
          echo "TEST: ${{ env.DYLD_LIBRARY_PATH }}"
          if [ ${{ matrix.os }} == ubuntu-18.04 ]
          then
            export LD_LIBRARY_PATH=${{ env.LD_LIBRARY_PATH }}
          fi
          if [ ${{ matrix.os }} == macos-latest ]
          then
            export DYLD_LIBRARY_PATH=${{ env.DYLD_LIBRARY_PATH }}
          fi
          cd DSPThirdPartyLibs
          ls bin
          ls lib
          ./bin/scip -v
